export const AppConstants = {
	DEBUG_MODE: false,
	DEFAULT_PAGE_SIZE: 10,
	DEFAULT_STORIES_DISPLAY_FORMAT: "TYPE_1",
	STORIES_DISPLAY_FORMATS: {
		TYPE_1: "NARROW TALL FORMAT",
		TYPE_2: "SHALOW WIDE FORMAT"
	},
	DEFAULT_FEED_CATEGORY_TAG: "news",
	DEFAULT_FEED_CATEGORY_FETCH_ID: "news",
	FEED_TYPES:{
		STANDALONE: {
			CATEGORY: "feedForSoriesWithinCategory",
			TOPIC: "feedForSoriesAboutTopic"
		},
		CONTEXTUAL: {
			TOPIC_IN_CATEGORY: "feedForSoriesAboutTopicWithinCategory",
		}
	},
	REMOTE_FETCH_PREFIX_NAMES: {
		ROOT: "ROOT",
		TOPIC: "TOPIC",
		TOP_TOPICS: "TOP_TOPICS",
		TRENDING_TOPICS: "TRENDING_TOPICS",
		CATEGORY: "CATEGORY",
		CATEGORIES: "CATEGORIES",
	},
	REMOTE_SECTION_NAMES: {
		CATEGORIES: "CATEGORIES",
		CATEGORY: "CATEGORY",
		TOPIC: "TOPIC",
		TOPIC_IN_CATEGORY: "TOPIC_IN_CATEGORY",
		TRENDING_TOPICS_IN_CATEGORY: "TRENDING_TOPICS_IN_CATEGORY",
		TOP_TOPICS_IN_CATEGORY: "TOP_TOPICS_IN_CATEGORY",
	},
	REMOTE_SECTION_URL_PREFIX: ``
}